site_name: Information and Communication Technologies 4ESO
use_directory_urls: false

nav:
  - "Presentation": "contents/unit00/presentation.md"
  # *************************************************************************
  # UNIT 1. Inside the Machine: Computer Architecture and Operating Systems
  # *************************************************************************
  - "Inside the machine":
      - "Inside the Machine: Computer Architecture and Operating Systems": "contents/unit01/unit1.md"
      - "1. Computer Architecture": # SB1.1
          - "Digital Information": "contents/unit01/digital_info.md"
          - "Digital Devices: An Overview": "contents/unit01/s11_intro.md"
          - "Personal computers": "contents/unit01/s11_personalcomputers.md"
          - "Mobile devices": "contents/unit01/s11_mobiledev.md"
          - "Other devices": "contents/unit01/s11_otherdev.md"
          #- "Digital Devices: An Introduction": "contents/devices/s12_intro.md"
          - "Computer Science": "contents/unit01/s12_computer_science.md"
          - "Hardware and Software": "contents/unit01/s12_hw_sw.md"
          - "Computer Components": "contents/unit01/s12_pc_main_components.md"
          - "Storage Devices": "contents/unit01/s12_storage_devices.md"
          - "Peripheral Devices": "contents/unit01/s12_peripheral.md"
    #- 'Web Programming':
    #  - 'Web Project': 'contents/htmlcss/webproject.md'
    #  - 'HTML': 'contents/htmlcss/html.md'
    #  - 'CSS': 'contents/htmlcss/css.md'
    #- 'Ada Lovelace':
    #  - 'Calculating Ada - The Countess of Computing': 'contents/ada.md'
    #- '2. Operating Systems': # SB1.1
    #  - 'Intro': ''
    # *************************************************************************
# UNIT 2. The Digital Highway: Communication Systems and the World of the Internet
# *************************************************************************
#- 'Unit 2. The Digital Highway':
#  - 'The Digital Highway: Communication Systems and the World of the Internet': 'contents/unit02/unit2.md'
# *************************************************************************
# UNIT 3. Creating the Future: Digital Content and Coding Essentials
# *************************************************************************
#- 'Unit 3. Creating the Future':
#  - 'Creating the Future: Digital Content and Coding Essentials': 'contents/unit03/unit3.md'
# *************************************************************************
# UNIT 4. Connecting Minds: Online Communication, Collaboration, and Publishing
# *************************************************************************
#- 'Unit 4. Connecting Minds':
#  - 'Connecting Minds: Online Communication, Collaboration, and Publishing': 'contents/unit04/unit4.md'
# *************************************************************************
# UNIT 5. Security and Well-being in Digital Spaces
# *************************************************************************
#- 'Unit 5. Security and Well-being':
#  - 'Security and Well-being in Digital Spaces': 'contents/unit05/unit5.md'
# *************************************************************************
# UNIT 6. Responsible Digital Citizenship: Privacy and Ethics in the Digital World
# *************************************************************************
#- 'Unit 6. Digital Citizenship':
#  - 'Responsible Digital Citizenship: Privacy and Ethics in the Digital World': 'contents/unit06/unit6.md'
#- 'Computer Systems':
#  - 'Coming soon': ''
#- 'Operating Systems':
#  - 'An introduction to Operating System':
#    - 'Hardware and Software': 'content/os/hw-sw.md'
#    - 'The Operating System: definitions': 'content/os/the-os.md'
#    - 'OS Properties': 'content/os/os-properties.md'
#  - 'Examples of Operating Systems':
#    - 'Windows, Mac and Linux': 'content/os/windows-macos-linux.md'
#    - 'Linux vs Windows': 'content/os/linux-vs-windows.md'
#  - 'Linux Commands' : 'content/os/linux-commands.md'

theme:
  language: es
  name: "readthedocs"
  palette:
    primary: "Teal"
    accent: "Teal"
  font:
    text: Roboto
    code: Roboto Mono
  logo: "images/floppy-ict4.png"
  features:
    - content.code.copy

plugins:
  - glightbox

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.arithmatex
  - codehilite:
  #    linenums: true
  - footnotes
  - meta
  - sane_lists
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.superfences

extra_css:
  - css/ict.css

extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML"
